apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loanlens-staging
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: loanlens-backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: loanlens-frontend
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
    target:
      kind: HorizontalPodAutoscaler
configMapGenerator:
  - name: loanlens-config
    behavior: merge
    literals:
      - spring-profile=staging
      - log-level=DEBUG
