apiVersion: v1
kind: ConfigMap
metadata:
  name: loanlens-config
  namespace: loanlens-prod
data:
  redis-host: "loanlens-redis"
  redis-port: "6379"
  spring-profile: "prod"
  log-level: "INFO"
  report-output-dir: "/tmp/loanlens-reports"
